### ISSUE TITLE
Segfault on macosx 10.8

### ISSUE THREAD

**Issue by eden** [dosx/node-vips#5]
Running the tests results in a segfault with the latest master under node 0.8.  Backtrace:

```
#0  0x00000001001758c9 in v8::internal::HandleScope::DeleteExtensions ()
#1  0x0000000100d90945 in RotateAsync (args=@0x7fff5fbff210) at node-vips.cc:159
#2  0x000000010013a31c in v8::internal::Builtin_HandleApiCall ()
#3  0x00003a3d6910618e in ?? ()
#4  0x00003a3d69368134 in ?? ()
#5  0x00003a3d691ef27b in ?? ()
#6  0x00003a3d691ef27b in ?? ()
#7  0x00003a3d691ed78d in ?? ()
#8  0x00003a3d691edd10 in ?? ()
#9  0x00003a3d691ab540 in ?? ()
#10 0x00003a3d691a3058 in ?? ()
#11 0x00003a3d691a2f36 in ?? ()
#12 0x00003a3d691ab3dc in ?? ()
#13 0x00003a3d691b028d in ?? ()
#14 0x00003a3d6912e82a in ?? ()
#15 0x00003a3d69124967 in ?? ()
#16 0x00003a3d69111417 in ?? ()
#17 0x000000010015d091 in v8::internal::Invoke ()
#18 0x000000010011bcac in v8::Function::Call ()
#19 0x00000001000090ff in node::Tick ()
#20 0x000000010004db49 in uv__run_check ()
#21 0x0000000100043478 in uv__run ()
#22 0x000000010004339f in uv_run ()
#23 0x0000000100008eb6 in node::Start ()
#24 0x0000000100000f24 in start ()
```

**Comment by c4milo** [comment]
I'm running into this same issue

**Comment by bobrik** [comment]
I've got backtrace on linux for segmentation fault:

```
bobrik@callisto ~/dev $ cat gdb.txt 
#0  operator-> (this=<optimized out>, this=<optimized out>, this=<optimized out>) at ../src/objects-inl.h:4577
#1  v8::internal::GetScriptWrapper (script=...) at ../src/handles.cc:367
#2  0xb745125f in v8::internal::MessageHandler::MakeMessageObject (type=0xb7610220 "uncaught_exception", loc=<optimized out>, args=..., stack_trace=..., stack_frames=...) at ../src/messages.cc:79
#3  0xb741061d in v8::internal::Isolate::DoThrow (this=<optimized out>, exception=<optimized out>) at ../src/isolate.cc:1144
#4  0xb74107ac in v8::internal::Isolate::Throw (this=0x8288038, exception=0x4f764bed, location=0xbfd83f10) at ../src/isolate.cc:946
#5  0xb748e5ea in v8::internal::Parser::ReportMessageAt (this=<optimized out>, source_location=..., type=<optimized out>, args=...) at ../src/parser.cc:814
#6  0xb749286c in ReportMessage (data=0xb761c7f5, type=<optimized out>, length=1, type=<optimized out>, this=<optimized out>, type=<optimized out>, args=<optimized out>) at ../src/parser.cc:790
#7  v8::internal::Parser::ReportUnexpectedToken (this=Unhandled dwarf expression opcode 0xba
) at ../src/parser.cc:3534
#8  0xb749e41b in v8::internal::Parser::ParsePrimaryExpression (this=<optimized out>, ok=Asked for position 0 of stack, stack only has 0 elements on it.
) at ../src/parser.cc:3653
#9  0xb749d7be in v8::internal::Parser::ParseMemberWithNewPrefixesExpression (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3447
#10 0xb749ca86 in ParseMemberExpression (ok=<optimized out>, this=<optimized out>, this=<optimized out>, ok=<optimized out>) at ../src/parser.cc:3417
#11 v8::internal::Parser::ParseLeftHandSideExpression (this=<optimized out>, ok=Unhandled dwarf expression opcode 0xf9
) at ../src/parser.cc:3310
#12 0xb749c809 in v8::internal::Parser::ParsePostfixExpression (this=<optimized out>, ok=<optimized out>) at ../src/parser.cc:3271
#13 0xb749c242 in v8::internal::Parser::ParseUnaryExpression (this=DWARF-2 expression error: DW_OP_reg operations must be used either alone or in conjuction with DW_OP_piece or DW_OP_bit_piece.
) at ../src/parser.cc:3262
#14 0xb749ada6 in v8::internal::Parser::ParseBinaryExpression (this=<optimized out>, prec=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3091
#15 0xb749ab20 in v8::internal::Parser::ParseConditionalExpression (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3064
#16 0xb749955a in v8::internal::Parser::ParseAssignmentExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2991
#17 0xb7499b18 in v8::internal::Parser::ParseExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0xb2
) at ../src/parser.cc:2972
#18 0xb74969ee in v8::internal::Parser::ParseExpressionOrLabelledStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2320
#19 0xb7490008 in v8::internal::Parser::ParseStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0xa7
) at ../src/parser.cc:1625
#20 0xb7492a51 in v8::internal::Parser::ParseBlock (this=<optimized out>, labels=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:1914
#21 0xb748ff4e in v8::internal::Parser::ParseStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0xa7
) at ../src/parser.cc:1535
#22 0xb7492d5e in v8::internal::Parser::ParseIfStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2394
#23 0xb749012d in v8::internal::Parser::ParseStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0xa7
) at ../src/parser.cc:1548
#24 0xb748b8f0 in ParseBlockElement (this=<optimized out>, labels=<optimized out>, ok=<optimized out>) at ../src/parser.cc:1500
#25 v8::internal::Parser::ParseSourceElements (this=<optimized out>, processor=Unhandled dwarf expression opcode 0xca
) at ../src/parser.cc:1036
#26 0xb748ddae in v8::internal::Parser::ParseFunctionLiteral (this=<optimized out>, function_name=..., name_is_strict_reserved=<optimized out>, function_token_position=
Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:4546
#27 0xb749dd14 in v8::internal::Parser::ParseMemberWithNewPrefixesExpression (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3441
#28 0xb749ca86 in ParseMemberExpression (ok=<optimized out>, this=<optimized out>, this=<optimized out>, ok=<optimized out>) at ../src/parser.cc:3417
#29 v8::internal::Parser::ParseLeftHandSideExpression (this=<optimized out>, ok=Unhandled dwarf expression opcode 0xf9
) at ../src/parser.cc:3310
#30 0xb749c809 in v8::internal::Parser::ParsePostfixExpression (this=<optimized out>, ok=<optimized out>) at ../src/parser.cc:3271
#31 0xb749c242 in v8::internal::Parser::ParseUnaryExpression (this=DWARF-2 expression error: DW_OP_reg operations must be used either alone or in conjuction with DW_OP_piece or DW_OP_bit_piece.
) at ../src/parser.cc:3262
#32 0xb749ada6 in v8::internal::Parser::ParseBinaryExpression (this=<optimized out>, prec=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3091
#33 0xb749ab20 in v8::internal::Parser::ParseConditionalExpression (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3064
#34 0xb749955a in v8::internal::Parser::ParseAssignmentExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2991
#35 0xb749d16e in v8::internal::Parser::ParseArguments (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:4240
#36 0xb749cc37 in v8::internal::Parser::ParseLeftHandSideExpression (this=<optimized out>, ok=Unhandled dwarf expression opcode 0xf9
) at ../src/parser.cc:3344
#37 0xb749c809 in v8::internal::Parser::ParsePostfixExpression (this=<optimized out>, ok=<optimized out>) at ../src/parser.cc:3271
#38 0xb749c242 in v8::internal::Parser::ParseUnaryExpression (this=DWARF-2 expression error: DW_OP_reg operations must be used either alone or in conjuction with DW_OP_piece or DW_OP_bit_piece.
) at ../src/parser.cc:3262
#39 0xb749ada6 in v8::internal::Parser::ParseBinaryExpression (this=<optimized out>, prec=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3091
#40 0xb749ab20 in v8::internal::Parser::ParseConditionalExpression (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3064
#41 0xb749955a in v8::internal::Parser::ParseAssignmentExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2991
#42 0xb7499b18 in v8::internal::Parser::ParseExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0xb2
) at ../src/parser.cc:2972
#43 0xb74969ee in v8::internal::Parser::ParseExpressionOrLabelledStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2320
#44 0xb7490008 in v8::internal::Parser::ParseStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0xa7
) at ../src/parser.cc:1625
#45 0xb7492a51 in v8::internal::Parser::ParseBlock (this=<optimized out>, labels=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:1914
#46 0xb748ff4e in v8::internal::Parser::ParseStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0xa7
) at ../src/parser.cc:1535
#47 0xb7492d5e in v8::internal::Parser::ParseIfStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2394
#48 0xb749012d in v8::internal::Parser::ParseStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0xa7
) at ../src/parser.cc:1548
#49 0xb7492d5e in v8::internal::Parser::ParseIfStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2394
#50 0xb749012d in v8::internal::Parser::ParseStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0xa7
) at ../src/parser.cc:1548
#51 0xb748b8f0 in ParseBlockElement (this=<optimized out>, labels=<optimized out>, ok=<optimized out>) at ../src/parser.cc:1500
#52 v8::internal::Parser::ParseSourceElements (this=<optimized out>, processor=Unhandled dwarf expression opcode 0xca
) at ../src/parser.cc:1036
#53 0xb748ddae in v8::internal::Parser::ParseFunctionLiteral (this=<optimized out>, function_name=..., name_is_strict_reserved=<optimized out>, function_token_position=
Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:4546
#54 0xb749dd14 in v8::internal::Parser::ParseMemberWithNewPrefixesExpression (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3441
#55 0xb749ca86 in ParseMemberExpression (ok=<optimized out>, this=<optimized out>, this=<optimized out>, ok=<optimized out>) at ../src/parser.cc:3417
#56 v8::internal::Parser::ParseLeftHandSideExpression (this=<optimized out>, ok=Unhandled dwarf expression opcode 0xf9
) at ../src/parser.cc:3310
#57 0xb749c809 in v8::internal::Parser::ParsePostfixExpression (this=<optimized out>, ok=<optimized out>) at ../src/parser.cc:3271
#58 0xb749c242 in v8::internal::Parser::ParseUnaryExpression (this=DWARF-2 expression error: DW_OP_reg operations must be used either alone or in conjuction with DW_OP_piece or DW_OP_bit_piece.
) at ../src/parser.cc:3262
#59 0xb749ada6 in v8::internal::Parser::ParseBinaryExpression (this=<optimized out>, prec=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3091
#60 0xb749ab20 in v8::internal::Parser::ParseConditionalExpression (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3064
#61 0xb749955a in v8::internal::Parser::ParseAssignmentExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2991
#62 0xb74996d5 in v8::internal::Parser::ParseAssignmentExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3017
#63 0xb7499b18 in v8::internal::Parser::ParseExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0xb2
) at ../src/parser.cc:2972
#64 0xb74969ee in v8::internal::Parser::ParseExpressionOrLabelledStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2320
#65 0xb7490008 in v8::internal::Parser::ParseStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0xa7
) at ../src/parser.cc:1625
#66 0xb748b8f0 in ParseBlockElement (this=<optimized out>, labels=<optimized out>, ok=<optimized out>) at ../src/parser.cc:1500
#67 v8::internal::Parser::ParseSourceElements (this=<optimized out>, processor=Unhandled dwarf expression opcode 0xca
) at ../src/parser.cc:1036
#68 0xb748ddae in v8::internal::Parser::ParseFunctionLiteral (this=<optimized out>, function_name=..., name_is_strict_reserved=<optimized out>, function_token_position=
Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:4546
#69 0xb749dd14 in v8::internal::Parser::ParseMemberWithNewPrefixesExpression (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3441
#70 0xb749ca86 in ParseMemberExpression (ok=<optimized out>, this=<optimized out>, this=<optimized out>, ok=<optimized out>) at ../src/parser.cc:3417
#71 v8::internal::Parser::ParseLeftHandSideExpression (this=<optimized out>, ok=Unhandled dwarf expression opcode 0xf9
) at ../src/parser.cc:3310
#72 0xb749c809 in v8::internal::Parser::ParsePostfixExpression (this=<optimized out>, ok=<optimized out>) at ../src/parser.cc:3271
#73 0xb749c242 in v8::internal::Parser::ParseUnaryExpression (this=DWARF-2 expression error: DW_OP_reg operations must be used either alone or in conjuction with DW_OP_piece or DW_OP_bit_piece.
) at ../src/parser.cc:3262
#74 0xb749ada6 in v8::internal::Parser::ParseBinaryExpression (this=<optimized out>, prec=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3091
#75 0xb749ab20 in v8::internal::Parser::ParseConditionalExpression (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3064
#76 0xb749955a in v8::internal::Parser::ParseAssignmentExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2991
#77 0xb7499b18 in v8::internal::Parser::ParseExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0xb2
) at ../src/parser.cc:2972
#78 0xb749de11 in v8::internal::Parser::ParsePrimaryExpression (this=<optimized out>, ok=Asked for position 0 of stack, stack only has 0 elements on it.
) at ../src/parser.cc:3639
#79 0xb749d7be in v8::internal::Parser::ParseMemberWithNewPrefixesExpression (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3447
#80 0xb749ca86 in ParseMemberExpression (ok=<optimized out>, this=<optimized out>, this=<optimized out>, ok=<optimized out>) at ../src/parser.cc:3417
#81 v8::internal::Parser::ParseLeftHandSideExpression (this=<optimized out>, ok=Unhandled dwarf expression opcode 0xf9
) at ../src/parser.cc:3310
#82 0xb749c809 in v8::internal::Parser::ParsePostfixExpression (this=<optimized out>, ok=<optimized out>) at ../src/parser.cc:3271
#83 0xb749c242 in v8::internal::Parser::ParseUnaryExpression (this=DWARF-2 expression error: DW_OP_reg operations must be used either alone or in conjuction with DW_OP_piece or DW_OP_bit_piece.
) at ../src/parser.cc:3262
#84 0xb749ada6 in v8::internal::Parser::ParseBinaryExpression (this=<optimized out>, prec=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3091
#85 0xb749ab20 in v8::internal::Parser::ParseConditionalExpression (this=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:3064
#86 0xb749955a in v8::internal::Parser::ParseAssignmentExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2991
#87 0xb7499b18 in v8::internal::Parser::ParseExpression (this=<optimized out>, accept_IN=<optimized out>, ok=Unhandled dwarf expression opcode 0xb2
) at ../src/parser.cc:2972
#88 0xb74969ee in v8::internal::Parser::ParseExpressionOrLabelledStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:2320
#89 0xb7490008 in v8::internal::Parser::ParseStatement (this=<optimized out>, labels=Unhandled dwarf expression opcode 0xa7
) at ../src/parser.cc:1625
#90 0xb748e8dc in v8::internal::Parser::ParseModuleElement (this=<optimized out>, labels=Asked for position 0 of stack, stack only has 0 elements on it.
) at ../src/parser.cc:1130
#91 0xb748b8bb in v8::internal::Parser::ParseSourceElements (this=<optimized out>, processor=Unhandled dwarf expression opcode 0xca
) at ../src/parser.cc:1034
#92 0xb748b452 in v8::internal::Parser::DoParseProgram (this=<optimized out>, info=Unhandled dwarf expression opcode 0xa6
) at ../src/parser.cc:645
#93 0xb748af1f in v8::internal::Parser::ParseProgram (this=<optimized out>) at ../src/parser.cc:590
#94 0xb74a539f in v8::internal::ParserApi::Parse (info=<optimized out>, parsing_flags=Unhandled dwarf expression opcode 0x0
) at ../src/parser.cc:5982
#95 0xb7330a4f in v8::internal::MakeFunctionInfo (info=Unhandled dwarf expression opcode 0xe7
) at ../src/compiler.cc:467
#96 0xb7330632 in v8::internal::Compiler::Compile (source=..., script_name=..., line_offset=<optimized out>, column_offset=read_sleb128: Corrupted DWARF expression.
) at ../src/compiler.cc:604
#97 0xb72e76cc in v8::Script::New (source=..., origin=<optimized out>, pre_data=<optimized out>, script_data=...) at ../src/api.cc:1550
#98 0xb72e7aa1 in v8::Script::Compile (source=..., origin=<optimized out>, pre_data=<optimized out>, script_data=...) at ../src/api.cc:1576
#99 0xb72e7c14 in v8::Script::Compile (source=..., file_name=..., script_data=...) at ../src/api.cc:1594
#100 0x0808b445 in node::WrappedScript::EvalMachine<(node::WrappedScript::EvalInputFlags)0, (node::WrappedScript::EvalContextFlags)0, (node::WrappedScript::EvalOutputFlags)0> (args=
Unhandled dwarf expression opcode 0x0
) at ../src/node_script.cc:393
#101 0x08089bf7 in node::WrappedScript::CompileRunInThisContext (args=...) at ../src/node_script.cc:301
#102 0xb7325b43 in HandleApiCallHelper<false> (isolate=<optimized out>, args=<optimized out>, isolate=<optimized out>) at ../src/builtins.cc:1146
#103 v8::internal::Builtin_HandleApiCall (args=..., isolate=Cannot access memory at address 0xc2b0100
) at ../src/builtins.cc:1164
#104 0x4170a376 in ?? ()
#105 0x41728b47 in ?? ()
#106 0x417285a3 in ?? ()
#107 0x417579cc in ?? ()
#108 0x4170e501 in ?? ()
#109 0x41728b9c in ?? ()
#110 0x417285a3 in ?? ()
#111 0x417575a0 in ?? ()
#112 0x417573ca in ?? ()
#113 0x41721899 in ?? ()
#114 0x4171308a in ?? ()
#115 0xb735a124 in v8::internal::Invoke (is_construct=<optimized out>, function=..., receiver=..., argc=<optimized out>, args=<optimized out>, has_pending_exception=<optimized out>)
    at ../src/execution.cc:118
#116 0xb7359c9a in v8::internal::Execution::Call (callable=..., receiver=..., argc=<optimized out>, argv=<optimized out>, pending_exception=<optimized out>, convert_receiver=<optimized out>)
    at ../src/execution.cc:179
#117 0xb7456c46 in v8::internal::Object::GetPropertyWithDefinedGetter (this=0x4f708c2d, receiver=<optimized out>, getter=Unhandled dwarf expression opcode 0x0
) at ../src/objects.cc:303
#118 0xb7456681 in v8::internal::JSObject::GetPropertyWithCallback (this=<optimized out>, receiver=Unhandled dwarf expression opcode 0xdf
) at ../src/objects.cc:223
#119 0xb74565f7 in v8::internal::Object::GetProperty (this=<optimized out>, receiver=<optimized out>, result=Cannot access memory at address 0x92b0100
) at ../src/objects.cc:651
#120 0xb73fafbd in v8::internal::LoadIC::Load (this=<optimized out>, state=Unhandled dwarf expression opcode 0xf7
) at ../src/ic.cc:934
#121 0xb73ffe98 in v8::internal::LoadIC_Miss (args=..., isolate=<optimized out>) at ../src/ic.cc:2088
#122 0x4170a376 in ?? ()
#123 0x4175729f in ?? ()
#124 0x4170e501 in ?? ()
#125 0x41756c8d in ?? ()
#126 0x41721899 in ?? ()
#127 0x4171308a in ?? ()
#128 0xb735a124 in v8::internal::Invoke (is_construct=<optimized out>, function=..., receiver=..., argc=<optimized out>, args=<optimized out>, has_pending_exception=<optimized out>)
    at ../src/execution.cc:118
#129 0xb7359c9a in v8::internal::Execution::Call (callable=..., receiver=..., argc=<optimized out>, argv=<optimized out>, pending_exception=<optimized out>, convert_receiver=<optimized out>)
    at ../src/execution.cc:179
#130 0xb72f8110 in v8::Function::Call (this=Unhandled dwarf expression opcode 0x5
) at ../src/api.cc:3667
#131 0xb6cb5f61 in (anonymous namespace)::TransformDone (req=0x82df860) at ../src/node-vips.cc:102
#132 0x080e0ac8 in uv__after_work (eio=0x82df888) at ../deps/uv/src/unix/fs.c:669
#133 0x080d58ef in eio_finish (req=<optimized out>) at ../deps/uv/src/unix/eio/eio.c:860
#134 0x080d3d12 in etp_poll (channel=<optimized out>, channel=<optimized out>) at ../deps/uv/src/unix/eio/eio.c:698
#135 eio_poll (channel=0x81b34b4) at ../deps/uv/src/unix/eio/eio.c:966
#136 0x080e6f89 in uv_eio_want_poll_notifier_cb (watcher=0x81b3508, status=0) at ../deps/uv/src/unix/uv-eio.c:46
#137 0x080d2945 in uv__async_io (loop=<optimized out>, handle=0x81b35b8, events=1) at ../deps/uv/src/unix/async.c:117
#138 0x080d371a in uv__io_rw (ev=0x81b3b78, w=0x81b35b8, events=1) at ../deps/uv/src/unix/core.c:622
#139 0x080d91ed in ev_invoke_pending (loop=<optimized out>) at ../deps/uv/src/unix/ev/ev.c:2145
#140 0x080d2c1f in uv__poll (loop=<optimized out>, loop=<optimized out>) at ../deps/uv/src/unix/core.c:248
#141 uv__run (loop=Asked for position 0 of stack, stack only has 0 elements on it.
) at ../deps/uv/src/unix/core.c:257
#142 0x080d2b37 in uv_run (loop=Asked for position 0 of stack, stack only has 0 elements on it.
) at ../deps/uv/src/unix/core.c:265
#143 0x080702d9 in node::Start (argc=<optimized out>, argv=Unhandled dwarf expression opcode 0x7
) at ../src/node.cc:2974
#144 0xb6e33606 in __libc_start_main () from /lib/libc.so.6
#145 0x08062281 in _start ()
quit
```

**Comment by eden** [comment]
This should be fixed with the last commit.
